### ISSUE TITLE
Unfortunately it is not working anymore

### ISSUE THREAD

**Issue by venaxyt** [mronion420/mail-spoofer-script#2]
It was working before but now even in your website it's not working anymore.. x(

**Comment by mronion420** [comment]
sorry sir I fixed the issue.... www.mailspoofer.ml
I'm working to fix the git repo as soon as possible

**Comment by mronion420** [comment]
@venaxyt cheak now its working now

**Comment by venaxyt** [comment]
![image](https://user-images.githubusercontent.com/81310818/179425783-ea02a21a-b449-4409-aa02-a53830d747c5.png)
sad times :( sorry for slow responses, but bro don't worry anyways i don't really need it

**Comment by venaxyt** [comment]
just an advice, use netlify instead of 000webhost, it sucks

**Comment by mronion420** [comment]
Download the whole repo and upload it on your hosting.... I've updated
